server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从服务在注册中心动态创建路由的功能
      routes: # 可以配置多个路由
        - id: payment_routh # 路由id，没有固定规则但要求唯一
          #          uri:  http://localhost:8001 # 匹配后提供服务的路由地址
          uri:  lb://cloud-payment-service
          predicates: #断言
            - Path=/payment/get/** # 路径相匹配的进行路由
            #- After=2020-06-28T16:27:25.116+08:00[Asia/Shanghai] 4点27前访问永远404
            #- Cookie=username,zs  cookie中必须包含的username = zs
            #- Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Method=Get
            #- Query=username, \d+  #要有参数名username并且值还是整数才能路由

        - id: payment_routh2 # 路由id，没有
          #          uri:  http://localhost:8001 # 匹配后提供服务的路由地址
          uri:  lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** # 路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka:  true
      fetch-registry:  true
      defaultZone: http://eureka7001.com:7001/eureka